# Generated by Django 5.1.4 on 2025-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clicktransaction',
            name='click_payment_id',
            field=models.CharField(max_length=255,  blank=True, null=True, help_text='click_paydoc_id'),
        ),
    ]
